server:
  port: 8081

spring:
  application:
    name: order
  cloud:
    sentinel:
      transport:
        dashboard: localhost:9000 # Dashboard host and port
        port: 8719                 # Port for communication with dashboard
    nacos:
      config:
        server-addr: localhost:8848
        file-extension: properties
  config:
    import: nacos:spring-alibaba-clubhouse
  datasource:
    url: jdbc:postgresql://localhost:5432/seata
    username: seata
    password: seata
    driver-class-name: org.postgresql.Driver
  # jpa:
  #   show-sql: true
  #   hibernate:
  #     ddl-auto: update

seata:
  enabled: true
  application-id: order-app
  tx-service-group: tx_group
  service:
    vgroup-mapping:
      tx_group: default
    grouplist:
      default: localhost:8091
  data-source-proxy-mode: AT

# Spring Boot Actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, env, loggers  # 启用常用监控端点
  health:
    diskspace:
      enabled: true
    redis:
      enabled: true
  metrics:
    enable:
      "[jvm.memory]": true
      "[jvm.buffer.memory.used]": true
      "[http.server.requests]": true
      